version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: postgres
    ports:
      - '49153:49153'
    volumes:
      - .:/home/node/app
    depends_on:
      - db

  db:
    build: docker/postgres
    container_name: postgres
    restart: always
    tty: true
    ports:
      - '49153:49153'
    volumes:
      - docker/dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
      POSTGRES_DB: postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpw
    ports:
      - '8000:80'
    depends_on:
      - db
    restart: always
